### ISSUE TITLE
expose data port and disable disk cache

### ISSUE THREAD

**Issue by L2501** [JackLiar/docker-acestream#1]
for better performance should forward the data port 8621
and disable the disk cache (--live-cache-type/--vod-cache-type memory) to prevent huge container files

**Comment by JackLiar** [comment]
Would forward the data port really enhance the performance? If so, how?

Since no outside client need to initialize the communication to acestreamengine, and the engine doesn't provide service through 8621, I think there is no need to expose port 8621 to the outside world.

I'm not a hardcore docker user, so I would like to know how it works.

The disk cache advice is awesome, thx man :)

**Comment by L2501** [comment]
Acestream is based on bittorrent p2p the default data port is 8621. opening this will improve connectivity and speeds as people who are behind NAT can then connect to you directly
